services:
  homeassistant:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - "./data:/config"
    environment:
      - TZ=${TIME_ZONE}
    image: homeassistant/home-assistant:2024.4.3
    labels:  
      createdBy: "Apps"
