version: '3'
services:
  yesplaymusic:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    image: fogforest/yesplaymusic:0.4.7
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
