services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:v1.13.0-alpha.33
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:7890"
    volumes:
      - ./data:/etc/sing-box/
    command:
      - -D /var/lib/sing-box -C /etc/sing-box/ run
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true