services:
  heimdall:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
      - "${PANEL_APP_PORT_HTTPS}:443"
    volumes:
      - "./data:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    image: linuxserver/heimdall:2.6.3
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
