services:
  postgres:
    container_name: ${CONTAINER_NAME}
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PANEL_DB_ROOT_USER}
      - POSTGRES_PASSWORD=${PANEL_DB_ROOT_PASSWORD}
    ports:
      - ${PANEL_APP_PORT_HTTP}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
