services:
  grafana:
    container_name: ${CONTAINER_NAME}
    image: grafana/grafana:12.0.1
    restart: always
    user: '0'
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    volumes:
      - ./data:/var/lib/grafana
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
