services:
  metabase:
    image: metabase/metabase:v0.52.5
    container_name: ${CONTAINER_NAME}
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./data/metabase:/metabase
      - ./data/metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: ${PANEL_DB_NAME}
      MB_DB_PORT: 3306
      MB_DB_USER: ${PANEL_DB_USER}
      MB_DB_PASS: ${PANEL_DB_USER_PASSWORD}
      MB_DB_HOST: ${PANEL_DB_HOST}
    labels:
      createdBy: "Apps"
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
networks:
  1panel-network:
    external: true