version: "3"
services:
  frps:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    volumes:
        - ./data/frps.toml:/etc/frp/frps.toml
    image: snowdreamtech/frps:0.56.0
    labels:  
      createdBy: "Apps"
