services:
  showdoc:
    image: star7th/showdoc:arm-latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    tty: true
    volumes:
      - /showdoc_data:/showdoc_data_old
      - ./showdocdata/html:/var/www/html
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true