services:
  ntfy:
    image: "binwiederhier/ntfy:v2.11.0"
    container_name: ${CONTAINER_NAME}
    command:
      - serve
    environment:
      - TZ=${TIME_ZONE}
    user: ${PUID}:${PGID}
    volumes:
      - ./data/cache/ntfy:/var/cache/ntfy
      - ./data/ntfy:/etc/ntfy
    ports:
      - "${PANEL_APP_PORT_HTTP}:${APP_PORT_INTERNAL}"
    restart: always
    networks:
      - 1panel-network
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:${APP_PORT_INTERNAL}/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
