services:
  redis:
    image: redis:6.2.17
    restart: always
    container_name: ${CONTAINER_NAME}
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:6379
    command: >
      sh -c '
      if [ -z "${PANEL_REDIS_ROOT_PASSWORD}" ]; then
        redis-server /etc/redis/redis.conf
      else
        redis-server /etc/redis/redis.conf --requirepass ${PANEL_REDIS_ROOT_PASSWORD}
      fi'
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./logs:/logs
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true