services:
  trend-radar:
    image: wantcat/trendradar:4.0.3
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    volumes:
      - ./config:/app/config:ro
      - ${DATA_PATH}:/app/output
    environment:
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - RUN_MODE=${RUN_MODE}
      - IMMEDIATE_RUN=${IMMEDIATE_RUN}
    networks:
      - 1panel-network
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
