services:
  mosdns-x:
    image: ghcr.io/787a68/mosdns-x:v25.12.05
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_DNS}:53/tcp
      - ${PANEL_APP_PORT_DNS}:53/udp
      - ${PANEL_APP_PORT_DOH}:9053/tcp
    volumes:
      - ./data:/etc/mosdns
    environment:
      - crontab=${CRONTAB}
    #  - crontabcnd=${CRONTABCDN}
    labels:  
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
