version: '3'
services:
  focalboard:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8000"
    volumes:
      - "./data/config.json:/opt/focalboard/config.json"   #sqlite
      #- "./data/postgres-config.json:/opt/focalboard/config.json"   #postgres，需要修改对应数据库信息
      - fbdata:/opt/focalboard/data
    image: mattermost/focalboard:7.11.2
    labels:  
      createdBy: "Apps"

volumes:
  fbdata:

networks:  
  1panel-network:  
    external: true
