version: '3'
services:
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - 1panel-network
    volumes:
      - ./conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true