services:
  casdoor:
    image: casbin/casdoor:v2.9.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8000
    environment:
      RUNNING_IN_DOCKER: "true"
      driverName: ${CASDOOR_DRIVER_NAME}
      dataSourceName: ${CASDOOR_DATASOURCE_NAME}
      dbName: ${PANEL_DB_NAME}
    volumes:
      - ./conf:/conf
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true