services:
  nexus:
    image: sonatype/nexus3:3.76.0
    restart: always
    container_name: ${CONTAINER_NAME}
    environment:
      - TZ=Asia/Shanghai
    ports:
      - ${PANEL_APP_PORT_HTTP}:8081
    volumes:
      - ./data:/nexus-data
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true