services:
  dashboard:
    image: ghcr.io/nezhahq/nezha:v1.13.2
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8008
    volumes:
      - ./data:/dashboard/data
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
