services:
  vllm:
    image: vllm/vllm-openai:v0.8.4
    container_name: ${CONTAINER_NAME}
    restart: always
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - 1panel-network
    volumes:
      - ./cache/huggingface:/root/.cache/huggingface
    environment:
      HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}
      HF_ENDPOINT: https://hf-mirror.com
    ports:
      - ${PANEL_APP_PORT_HTTP}:8000
    ipc: host
    command: --model ${MODEL}
networks:
  1panel-network:
    external: true
