version: '3'
services:
  tailchat:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    image: moonrailgun/tailchat:1.8.3
    networks:
      - 1panel-network
    environment:
      - SERVICEDIR=services,plugins
      - LOGGER=true
      - LOGLEVEL=info
      - PORT=11000
      - REDIS_URL=redis://:${REDIS_PASS}@${REDIS_HOST}:${REDIS_PORT}
      - TRANSPORTER=redis://:${REDIS_PASS}@${REDIS_HOST}:${REDIS_PORT}
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin
      - MINIO_URL=${MINIO_HOST}:${MINIO_PORT}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASS=${MINIO_PASS}
      - SMTP_SENDER=${SMTP_SENDER}
      - SMTP_URI=${SMTP_URI}
      - SECRET=${SECRET}
      - API_URL=${API_URL}
    ports:
      - ${PANEL_APP_PORT_HTTP}:11000
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
