services:
  clickhouse:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8123"
      - "${PANEL_APP_PORT_TCP}:9000"
    volumes:
      - ./clickhouse:/var/lib/clickhouse/
      - ./clickhouse-server:/var/log/clickhouse-server/
    image: clickhouse/clickhouse-server:24.12.2-alpine
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
