services:
  frpc:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    volumes:
        - ./data/frpc.toml:/etc/frp/frpc.toml
        - ./data/ssl:/etc/frp/ssl
    image: snowdreamtech/frpc:0.58.0
    labels:  
      createdBy: "Apps"
