services:
  jenkins:
    container_name: ${CONTAINER_NAME}
    image: jenkins/jenkins:2.479.3-lts
    restart: always
    privileged: true
    user: root
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_BINARY}:${DOCKER_BINARY}
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
