services:
  maxkb:
    image: 1panel/maxkb:v2.0.2
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    networks:
      - 1panel-network
    volumes:
      - ./data:/opt/maxkb
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
