services:
  redpanda-console:
    image: redpandadata/console:v2.8.2
    restart: always
    container_name: ${CONTAINER_NAME}
    networks:
      - 1panel-network
    environment:
      KAFKA_BROKERS: ${KAFKA_HOST}:9092
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
