services:
  ollama:
    image: 1panel/maxkb:v1.1.3
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    networks:
      - 1panel-network
    volumes:
      - ./data:/var/lib/postgresql/data
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
