services:
  sonarqube:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    image: sonarqube:10.7.0-community
    ports:
      - ${PANEL_APP_PORT_HTTP}:9000
    volumes:
      - ./data/data:/opt/sonarqube/data
      - ./data/extensions:/opt/sonarqube/extensions
      - ./data/logs:/opt/sonarqube/logs
    environment:
      SONAR_JDBC_URL: jdbc:${PANEL_DB_TYPE}://${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}
      SONAR_JDBC_USERNAME: ${PANEL_DB_USER}
      SONAR_JDBC_PASSWORD: ${PANEL_DB_USER_PASSWORD}
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true