networks:  
  1panel-network:  
    external: true
services:
  wavelog-main:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/wavelog/wavelog:2.2.1
    environment:
      CI_ENV: docker
    networks:  
      - 1panel-network 
    volumes:
      - ./data/wavelog-config:/var/www/html/application/config/docker
      - ./data/wavelog-uploads:/var/www/html/uploads
      - ./data/wavelog-userdata:/var/www/html/userdata
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    restart: always
    labels:  
      createdBy: "Apps"  

