services:
  meilisearch:
    container_name: ${CONTAINER_NAME}
    networks:
      - 1panel-network
    image: getmeili/meilisearch:v1.8.1
    command:
      - /bin/sh
      - -c
      - /bin/meilisearch ${MEILI_NO_ANALYTICS}
    labels:
      createdBy: Apps
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:7700
    environment:
      MEILI_CONFIG_FILE_PATH: /config/config.toml
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - ./config:/config 
      - ./data:/meili_data
      - ./dumps:/dumps
      - ./snapshots:/snapshots
networks:
  1panel-network:
    external: true