services:
  litespeed:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./data/lsws/conf:/usr/local/lsws/conf
      - ./data/lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./data/bin/container:/usr/local/bin
      - ./data/sites:/var/www/vhosts/
      - ./data/acme:/root/.acme.sh/
      - ./data/logs:/usr/local/lsws/logs/
    ports:
      - "${PANEL_APP_PORT_HTTP_80}:80"
      - "${PANEL_APP_PORT_HTTPS}:443"
      - "${PANEL_APP_PORT_HTTPS}:443/udp"
      - "${PANEL_APP_PORT_HTTP}:7080"
    environment:
      - TZ=${TIME_ZONE}
    image: litespeedtech/openlitespeed:1.8.1-lsphp74
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
