services:
  sub-store:
    image: xream/sub-store:2.20.54-http-meta
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3001"
    environment:
      - SUB_STORE_PUSH_SERVICE=${SUB_STORE_PUSH_SERVICE} # 推送服务 URL
      - SUB_STORE_BACKEND_SYNC_CRON=55 23 * * * # 定时备份
      - SUB_STORE_BACKEND_MERGE=true # 启用后端合并功能
      - SUB_STORE_FRONTEND_BACKEND_PATH=${SUB_STORE_FRONTEND_BACKEND_PATH} # 前端后端路径
    volumes:
      - ./data:/opt/app/data
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true