services:
  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:12.6.2
    container_name: ${CONTAINER_NAME}
    privileged: ${PRIVILEGED}
    restart: always
    user: root
    command: /data/scripts/register.sh
    volumes:
      - ./data:/data
      - ./scripts/register.sh:/data/scripts/register.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - FORGEJO_INSTANCE_URL=${FORGEJO_INSTANCE_URL}
      - RUNNER_REGISTRATION_TOKEN=${RUNNER_REGISTRATION_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME}
      - RUNNER_LABELS=${RUNNER_LABELS}
    networks:
      - 1panel-network
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
