services:
  couchdb:
    image: couchdb:3.4.2
    container_name: ${CONTAINER_NAME}
    environment:
      - COUCHDB_USER=${OBSIDIAN_LIVESYNC_USER} 
      - COUCHDB_PASSWORD=${OBSIDIAN_LIVESYNC_USER_PASSWORD}
    volumes:
      - ./data:/opt/couchdb/data
      - ./conf/local.ini:/opt/couchdb/etc/local.ini
    ports:
      - ${PANEL_APP_PORT_HTTP}:5984
    restart: unless-stopped
    networks:
      - 1panel-network
    labels:  
      createdBy: "Apps" 
networks:  
  1panel-network:  
    external: true