services:
  onedev:
    image: 1dev/server:11.6.9
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:6610"
      - "${PANEL_APP_PORT_SSH}:6611"
    volumes:
      - ./data:/opt/onedev
      - /var/run/docker.sock:/var/run/docker.sock
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
