services:
  jellyfin:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
        - "${PANEL_APP_PORT_HTTP}:8096"
    volumes:
        - "./data/config:/config"
        - "${CACHE_FOLDER_PATH}:/cache"
        - "${MEDIA_FOLDER_PATH}:/media/media"
    image: "jellyfin/jellyfin:10.10.3"
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true