services:
  homeassistant:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "./data:/config"
      - "/run/dbus:/run/dbus:ro"
    environment:
      - TZ=${TIME_ZONE}
    image: homeassistant/home-assistant:2026.2.1
    labels:  
      createdBy: "Apps"
