services:
  mariadb:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    image: mariadb:11.6.2
    ports:
      - ${PANEL_APP_PORT_HTTP}:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${PANEL_DB_ROOT_PASSWORD}
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true