services:
  mkdocs-material:
    image: squidfunk/mkdocs-material:9.5.49
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8000"
    volumes:
      - ./data:/docs
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true