services:
  cloudflared:
    image: cloudflare/cloudflared:2025.1.0
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: 1panel-network
    command: tunnel --no-autoupdate run --token ${token}
    labels:  
      createdBy: "Apps"
networks:
    1panel-network:
        external: true